{% set version = "3" %}

package:
  name: isis3
  version: {{ version }}

source:
  git_url: 'https://github.com/USGS-Astrogeology/ISIS3.git'
  git_branch: dev

build:
  number: 0


# Shotgun strat on requirements until we can narrow them down
requirements:
  build:
    - armadillo==8.200.0 
    - pcl==1.8.1
    - geos==3.5.1
    - protobuf==3.5.2
    - libprotobuf==3.5.2
    - qwt=6.1.3
    - sip==4.18
    - mysql==5.7.20
    - ninja==1.7.2=0
    - xorg-libsm
    - xorg-libxi
    - xorg-libice
    - pip==9.0.1
    - setuptools=38.5.1
    - wheel==0.30.0
    - xerces-c==3.1.4=0
    - zlib==1.2.11=0
    - blas==1.1=openblas
    - bzip2==1.0.6=1
    - cmake==3.9.1=0
    - cspice==66-0
    - curl
    - doxygen==1.8.14=0
    - eigen==3.3.3=0
    - embree==2.14.0=0
    - geotiff==1.4.2=1
    - gmp==6.1.2=0
    - gsl==2.2.1=blas_openblas_3
    - hdf5==1.8.18=2
    - icu==58.2=0
    - jpeg==9b=2
    - krb5==1.14.2=0
    - libpng>=1.6.34
    - libtiff==4.0.9=0
    - libxml2==2.9.7=0
    - mesalib==17.2.0=0
    - mysql-connector-c==6.1.6=0
    - nn==1.86.0=2
    - openblas==0.2.19=2
    - opencv==3.3.0
    - nanoflann==1.2.2
    - gmm==5.0
    - jama==125
    - openssl==1.0.2n=0
    - python==3.6
    - sqlite==3.13.0=1
    - suitesparse==4.5.4=blas_openblas_200
    - superlu==5.2.1=blas_openblas_201
    - xorg-kbproto==1.0.7=1
    - xorg-libx11==1.6.4=6
    - bz2file==0.98
    - bullet==2.86.1=0
    - qhull==7.2.0=0
    - qt=5.9.6
    - tnt==126=0
    - xalan-c==1.11
    - x264==20131218
    - make
    - kakadu==1
  run:
    - armadillo==8.200.0 
    - pcl==1.8.1
    - geos==3.5.1
    - protobuf==3.5.2
    - libprotobuf==3.5.2
    - qwt=6.1.3
    - sip==4.18
    - mysql==5.7.20
    - ninja==1.7.2=0
    - xorg-libsm
    - xorg-libxi
    - xorg-libice
    - pip==9.0.1
    - setuptools=38.5.1
    - wheel==0.30.0
    - xerces-c==3.1.4=0
    - zlib==1.2.11=0
    - blas==1.1=openblas
    - bzip2==1.0.6=1
    - cmake==3.9.1=0
    - cspice==66-0
    - curl
    - doxygen==1.8.14=0
    - eigen==3.3.3=0
    - embree==2.14.0=0
    - geotiff==1.4.2=1
    - gmp==6.1.2=0
    - gsl==2.2.1=blas_openblas_3
    - hdf5==1.8.18=2
    - icu==58.2=0
    - jpeg==9b=2
    - krb5==1.14.2=0
    - libpng>=1.6.34
    - libtiff==4.0.9=0
    - libxml2==2.9.7=0
    - mesalib==17.2.0=0
    - mysql-connector-c==6.1.6=0
    - nn==1.86.0=2
    - openblas==0.2.19=2
    - opencv==3.3.0
    - nanoflann==1.2.2
    - gmm==5.0
    - jama==125
    - openssl==1.0.2n=0
    - python==3.6
    - sqlite==3.13.0=1
    - suitesparse==4.5.4=blas_openblas_200
    - superlu==5.2.1=blas_openblas_201
    - xorg-kbproto==1.0.7=1
    - xorg-libx11==1.6.4=6
    - bz2file==0.98
    - bullet==2.86.1=0
    - qhull==7.2.0=0
    - qt=5.9.6
    - tnt==126=0
    - xalan-c==1.11
    - x264==20131218
    - make
    - kakadu==1
# Add the tests eventually
# test:
#

# about:
#   home: https://developers.google.com/protocol-buffers/
#   license: BSD 3-Clause
#   license_file: LICENSE
#   summary: "Protocol Buffers - Google's data interchange format."

# extra:
#   recipe-maintainers:
